class CfgAmmo {
    class BulletBase;
    class B_127x99_Ball: BulletBase {
        CraterEffects = QGVAR(noFX);
        explosionEffects = QGVAR(noFX);
        class HitEffects {
            vehicle = QGVAR(impactMetal_API);
            object = QGVAR(impactConcrete_API);
            hitGlass = QGVAR(impactGlass_API);
            hitGlassArmored = QGVAR(impactGlassThin_API);
            hitWood = QGVAR(impactWood_API);
            hitMetal = QGVAR(impactMetal_API);
            hitMetalPlate = QGVAR(impactMetal_API);
            hitPlaster = QGVAR(impactPlaster_API);
            hitRubber = QGVAR(impactRubber_API);
            hitConcrete = QGVAR(impactConcrete_API);
            hitMan = QGVAR(impactBlood_API);
            hitBuilding = QGVAR(impactPlaster_API);
            hitVirtual = QGVAR(impactMetal_API);
            hitGroundSoft = QGVAR(explosionAmmoCrater_API);
            hitGroundRed = QGVAR(explosionAmmoCrater_API);
            hitGroundHard = QGVAR(explosionAmmoCrater_API);
            hitHay = QGVAR(impactHay_API);
            hitPlastic = QGVAR(impactPlastic_API);
            hitTyre = QGVAR(impactTyre_API);
        };
    };
    class B_127x99_SLAP: B_127x99_Ball {
        CraterEffects = QGVAR(noFX);
        explosionEffects = QGVAR(noFX);
        class HitEffects {
            vehicle = QGVAR(impactMetal_API);
            object = QGVAR(impactConcrete_API);
            hitGlass = QGVAR(impactGlass_API);
            hitGlassArmored = QGVAR(impactGlassThin_API);
            hitWood = QGVAR(impactWood_API);
            hitMetal = QGVAR(impactMetal_API);
            hitMetalPlate = QGVAR(impactMetal_API);
            hitPlaster = QGVAR(impactPlaster_API);
            hitRubber = QGVAR(impactRubber_API);
            hitConcrete = QGVAR(impactConcrete_API);
            hitMan = QGVAR(impactBlood_API);
            hitBuilding = QGVAR(impactPlaster_API);
            hitVirtual = QGVAR(impactMetal_API);
            hitGroundSoft = QGVAR(explosionAmmoCrater_API);
            hitGroundRed = QGVAR(explosionAmmoCrater_API);
            hitGroundHard = QGVAR(explosionAmmoCrater_API);
            hitHay = QGVAR(impactHay_API);
            hitPlastic = QGVAR(impactPlastic_API);
            hitTyre = QGVAR(impactTyre_API);
        };
    };
    class B_127x108_Ball: BulletBase {
        CraterEffects = QGVAR(noFX);
        explosionEffects = QGVAR(noFX);
        class HitEffects {
            vehicle = QGVAR(impactMetal_API);
            object = QGVAR(impactConcrete_API);
            hitGlass = QGVAR(impactGlass_API);
            hitGlassArmored = QGVAR(impactGlassThin_API);
            hitWood = QGVAR(impactWood_API);
            hitMetal = QGVAR(impactMetal_API);
            hitMetalPlate = QGVAR(impactMetal_API);
            hitPlaster = QGVAR(impactPlaster_API);
            hitRubber = QGVAR(impactRubber_API);
            hitConcrete = QGVAR(impactConcrete_API);
            hitMan = QGVAR(impactBlood_API);
            hitBuilding = QGVAR(impactPlaster_API);
            hitVirtual = QGVAR(impactMetal_API);
            hitGroundSoft = QGVAR(explosionAmmoCrater_API);
            hitGroundRed = QGVAR(explosionAmmoCrater_API);
            hitGroundHard = QGVAR(explosionAmmoCrater_API);
            hitHay = QGVAR(impactHay_API);
            hitPlastic = QGVAR(impactPlastic_API);
            hitTyre = QGVAR(impactTyre_API);
        };
    };
    class B_127x108_APDS: B_127x108_Ball {
        CraterEffects = QGVAR(noFX);
        explosionEffects = QGVAR(noFX);
        class HitEffects {
            vehicle = QGVAR(impactMetal_API);
            object = QGVAR(impactConcrete_API);
            hitGlass = QGVAR(impactGlass_API);
            hitGlassArmored = QGVAR(impactGlassThin_API);
            hitWood = QGVAR(impactWood_API);
            hitMetal = QGVAR(impactMetal_API);
            hitMetalPlate = QGVAR(impactMetal_API);
            hitPlaster = QGVAR(impactPlaster_API);
            hitRubber = QGVAR(impactRubber_API);
            hitConcrete = QGVAR(impactConcrete_API);
            hitMan = QGVAR(impactBlood_API);
            hitBuilding = QGVAR(impactPlaster_API);
            hitVirtual = QGVAR(impactMetal_API);
            hitGroundSoft = QGVAR(explosionAmmoCrater_API);
            hitGroundRed = QGVAR(explosionAmmoCrater_API);
            hitGroundHard = QGVAR(explosionAmmoCrater_API);
            hitHay = QGVAR(impactHay_API);
            hitPlastic = QGVAR(impactPlastic_API);
            hitTyre = QGVAR(impactTyre_API);
        };
    };
    class B_127x54_Ball: BulletBase {
        CraterEffects = QGVAR(noFX);
        explosionEffects = QGVAR(noFX);
        class HitEffects {
            vehicle = QGVAR(impactMetal_API);
            object = QGVAR(impactConcrete_API);
            hitGlass = QGVAR(impactGlass_API);
            hitGlassArmored = QGVAR(impactGlassThin_API);
            hitWood = QGVAR(impactWood_API);
            hitMetal = QGVAR(impactMetal_API);
            hitMetalPlate = QGVAR(impactMetal_API);
            hitPlaster = QGVAR(impactPlaster_API);
            hitRubber = QGVAR(impactRubber_API);
            hitConcrete = QGVAR(impactConcrete_API);
            hitMan = QGVAR(impactBlood_API);
            hitBuilding = QGVAR(impactPlaster_API);
            hitVirtual = QGVAR(impactMetal_API);
            hitGroundSoft = QGVAR(explosionAmmoCrater_API);
            hitGroundRed = QGVAR(explosionAmmoCrater_API);
            hitGroundHard = QGVAR(explosionAmmoCrater_API);
            hitHay = QGVAR(impactHay_API);
            hitPlastic = QGVAR(impactPlastic_API);
            hitTyre = QGVAR(impactTyre_API);
        };
    };
};
