class CfgCloudlets {
    class Default;
    class Missile2_vanilla: Default {
        interval = "0.003";
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        angleVar = 1;
        particleFSLoop = 0;
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 1.2;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1;
        volume = 0.8;
        rubbing = 0.5;
        size[] = {1,2};
        color[] = {{0.4,0.4,0.4,0.07},{0.6,0.6,0.6,0}};
        animationSpeed[] = {5};
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0;
        positionVar[] = {0.3,0.3,0.3};
        MoveVelocityVar[] = {1.2,1.2,1.2};
        rotationVelocityVar = 20;
        sizeVar = 0.2;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class Missile2Med_vanilla: Default {
        interval = "0.006";
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        angleVar = 1;
        particleFSLoop = 0;
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.6;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1;
        volume = 0.8;
        rubbing = 0.5;
        size[] = {1,2};
        color[] = {{0.4,0.4,0.4,0.07},{0.6,0.6,0.6,0}};
        animationSpeed[] = {5};
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0;
        positionVar[] = {0.3,0.3,0.3};
        MoveVelocityVar[] = {1.2,1.2,1.2};
        rotationVelocityVar = 20;
        sizeVar = 0.2;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class Missile3_vanilla: Default {
        interval = 0.001;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        angleVar = 1;
        particleFSLoop = 0;
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 2;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1;
        volume = 0.8;
        rubbing = 0.5;
        size[] = {1,2,2.8};
        color[] = {{0.5,0.5,0.5,0.07},{0.6,0.6,0.6,0.02},{0.7,0.7,0.7,0.01},{0.8,0.8,0.8,0.005},{0.9,0.9,0.9,0.003}};
        animationSpeed[] = {5};
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0.2;
        positionVar[] = {0.3,0.3,0.3};
        MoveVelocityVar[] = {0.4,0.4,0.4};
        rotationVelocityVar = 20;
        sizeVar = 0.15;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class Missile3Med_vanilla: Default {
        interval = 0.003;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        angleVar = 1;
        particleFSLoop = 0;
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.8;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1;
        volume = 0.8;
        rubbing = 0.5;
        size[] = {1,2,2.8};
        color[] = {{0.5,0.5,0.5,0.07},{0.6,0.6,0.6,0.02},{0.7,0.7,0.7,0.01},{0.8,0.8,0.8,0.005},{0.9,0.9,0.9,0.003}};
        animationSpeed[] = {5};
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0.2;
        positionVar[] = {0.3,0.3,0.3};
        MoveVelocityVar[] = {0.4,0.4,0.4};
        rotationVelocityVar = 20;
        sizeVar = 0.15;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class Missile4_vanilla: Default {
        circleVelocity[] = {0,0,0};
        moveVelocity[] = {0,0,0};
        size[] = {2.7,3};
        color[] = {{0.8,0.8,0.8,0.05},{1,1,1,0}};
        animationSpeed[] = {1};
        blockAIVisibility = 0;
        positionVar[] = {0.3,0.3,0.3};
        MoveVelocityVar[] = {0.4,0.4,0.4};
        colorVar[] = {0,0,0,0};
        interval = 0.0025;
        circleRadius = 0;
        angleVar = 1;
        particleFSLoop = 0;
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 12;
        particleFSFrameCount = 8;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 8;
        rotationVelocity = 1;
        weight = 1.24;
        volume = 1;
        rubbing = 1;
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0.1;
        rotationVelocityVar = 20;
        sizeVar = 0.2;
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        position[] = {0,0,0};
        positionVarConst[] = {0,0,0};
        MoveVelocityVarConst[] = {0,0,0};
        colorCoef[] = {1,1,1,1};
        angle = 0;
        sizeCoef = 1;
        animationSpeedCoef = 1;
    };
    class ArtilleryShell1_vanilla: Default {
        interval = 0.0035;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal_02";
        particleFSNtieth = 8;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 0;
        angleVar = 1;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.5;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1.23;
        volume = 1;
        rubbing = 0.2;
        size[] = {0.6,1.8,2.5};
        sizeCoef = 1;
        color[] = {{0.5,0.5,0.5,0.14},{0.6,0.6,0.6,0.06},{0.7,0.7,0.7,0.02},{0.8,0.8,0.8,0.006},{0.9,0.9,0.9,0.001}};
        colorCoef[] = {1,1,1,1};
        animationSpeed[] = {5};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 0.1;
        randomDirectionIntensity = 0.1;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0.2;
        positionVar[] = {0.08,0.08,0.08};
        MoveVelocityVar[] = {0.3,0.3,0.3};
        rotationVelocityVar = 20;
        sizeVar = 0.15;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
};

class Missile2 {
    class Missile2;
    class Missile2Med;
};
class Missile2_vanilla: Missile2 {
    class Missile2: Missile2 {
        type = "Missile2_vanilla";
    };
    class Missile2Med: Missile2Med {
        type = "Missile2Med_vanilla";
    };
};

class Missile3 {
    class Missile3;
    class Missile3Med;
};
class Missile3_vanilla: Missile3 {
    class Missile3: Missile3 {
        type = "Missile3_vanilla";
    };
    class Missile23ed: Missile3Med {
        type = "Missile3Med_vanilla";
    };
};

class Missile4 {
    class Missile4;
};
class Missile4_vanilla: Missile4 {
    class Missile4: Missile4 {
        type = "Missile4_vanilla";
    };
};

class ArtilleryTrails {
    class Trail1;
};

class ArtilleryTrails_vanilla: ArtilleryTrails {
    class Trail1: Trail1 {
        type = "ArtilleryShell1_vanilla";
    };
};
