// Mission Defines
#define ARTILLERY_MISSION_MIN_DELAY 5
#define ARTILLERY_MISSION_MIN_LENGTH 5
#define ARTILLERY_MISSION_DEF_LENGTH 180
#define ARTILLERY_ELLIPSE_COMPRESSION 1.6

#define ARTILLERY_MISSIONTYPE_UNDEF -1
#define ARTILLERY_MISSIONTYPE_LAZY 0
#define ARTILLERY_MISSIONTYPE_LAZY_WALK 10
#define ARTILLERY_MISSIONTYPE_LAZY_BARRAGE 3
#define ARTILLERY_MISSIONTYPE_QUICK_LAZY 1
#define ARTILLERY_MISSIONTYPE_QUICK_LAZY_WALK 11
#define ARTILLERY_MISSIONTYPE_QUICK_LAZY_BARRAGE 3
#define ARTILLERY_MISSIONTYPE_BRACKET 2
#define ARTILLERY_MISSIONTYPE_BRACKET_SHOTS 12
#define ARTILLERY_MISSIONTYPE_BRACKET_BARRAGE 3
#define ARTILLERY_MISSIONTYPE_POINT 3
#define ARTILLERY_MISSIONTYPE_LINEAR 4
#define ARTILLERY_MISSIONTYPE_LINEAR_WITH_BRACKET 5
#define ARTILLERY_MISSIONTYPE_LINEAR_BRACKET 12
#define ARTILLERY_MISSIONTYPE_LINEAR_BARRAGE 4
#define ARTILLERY_MISSIONTYPE_CREEPING 6
#define ARTILLERY_MISSIONTYPE_SLOW 7
#define ARTILLERY_MISSIONTYPE_SLOW_WITH_WALK 8
#define ARTILLERY_MISSIONTYPE_SLOW_WALK 10
#define ARTILLERY_MISSIONTYPE_SLOW_BARRAGE 7
#define ARTILLERY_MISSIONTYPE_SLOW_QUICK_LAZY 9
#define ARTILLERY_MISSIONTYPE_SLOW_QUICK_LAZY_WALK 11
#define ARTILLERY_MISSIONTYPE_SLOW_QUICK_LAZY_BARRAGE 7
#define ARTILLERY_SLOWBARRAGE_TIMER [ARTILLERY_MISSIONTYPE_SLOW,ARTILLERY_MISSIONTYPE_SLOW_WITH_WALK,ARTILLERY_MISSIONTYPE_SLOW_QUICK_LAZY]
#define ARTILLERY_REPORT_ON_COMPLETION [ARTILLERY_MISSIONTYPE_LAZY_WALK,ARTILLERY_MISSIONTYPE_BRACKET_SHOTS,ARTILLERY_MISSIONTYPE_QUICK_LAZY_WALK]

#define ARTILLERY_MISSION_STATUS_FREE   -1
#define ARTILLERY_MISSION_STATUS_WAIT    0
#define ARTILLERY_MISSION_STATUS_ASSIGN  1
#define ARTILLERY_MISSION_STATUS_FIRING  2

#define ARTILLERY_POSITIONS_QUICKLAZYADJUST [150, 350]
#define ARTILLERY_POSITIONS_LAZYADJUST [150, 300, 500]
#define ARTILLERY_POSITIONS_BRACKET(dispersion) [200 max dispersion, 300 max dispersion, -500]
