TRACE_1("",QUOTE(ADDON));

PREP(manInitEH);
PREP(setFog);
PREP(setSkillsDialogLoad);
PREP(setSkillsDialogSet);
PREP(setSkillsDialogSliderChange);
PREP(setSkillsLocal);
PREP(setSkillsModule);
PREP(setTime);
PREP(setWeather);
PREP(sideMarker);
PREP(skillDebug);
PREP(toolboxAttributeLoad);
PREP(toolboxAttributeSave);
PREP(zeus_banziCharge);
PREP(zeus_missionHint);
PREP(zeusAttributes);
PREP(zeusAttributes_missionHint);
