#include "\z\potato\addons\reinforceToHC\script_component.hpp"

#define DISPLAY_NAME_INDEX 0
#define SIDE_INDEX 1
#define ADDON_CLASS_INDEX 2
#define VEHICLE_POOL_START_INDEX 3
#define SCOUT_UNIT_POOL_INDEX 3
#define FIRST_SPECIFIC_LZ_OR_RP_OPTION_INDEX 4
#define UNARMED_HELO_UNIT_POOL_INDEX 7
#define ARMED_HELO_UNIT_POOL_INDEX 8
#define UNARMED_BOAT_UNIT_POOL_INDEX 9
#define ARMED_BOAT_UNIT_POOL_INDEX 10
#define INFANTRY_UNIT_POOL_INDEX 11
