class CfgMagazines {
    CREATE_MAGAZINES(CUP_30Rnd_105mmHE_M119_M,CUP_Sh_105_HE);
    CREATE_MAGAZINES(CUP_30Rnd_122mmHE_D30_M,CUP_Sh_122_HE);
    CREATE_MAGAZINES(CUP_12Rnd_MLRS_HE,CUP_R_MLRS_HE);
    CREATE_MAGAZINES(CUP_40Rnd_GRAD_HE,CUP_R_GRAD_HE);
};
