#define COMPONENT zeusHC
#include "\z\potato\addons\core\script_mod.hpp"

#define DEBUG_MODE_FULL
#define DISABLE_COMPILE_CACHE
#define CBA_DEBUG_SYNCHRONOUS

#ifdef DEBUG_ENABLED_ZEUSHC
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_ZEUSHC
    #define DEBUG_SETTINGS DEBUG_SETTINGS_ZEUSHC
#endif

// display defines
#define BUILD_GROUP_BG_IDC 212453
#define BUILD_GROUP_IDD 796475
#define BUILD_GROUP_FRAME_IDC 164739
#define BUILD_GROUP_CANCEL_IDC 362181
#define BUILD_GROUP_OK_IDC 486369
#define BUILD_GROUP_FACTIONS_IDC 149743
#define BUILD_GROUP_UNITS_IDC 136824
#define BUILD_GROUP_TO_ADD_IDC 158049
#define BUILD_GROUP_ADD_IDC 595106
#define BUILD_GROUP_REMOVE_IDC 819477

#define BUILD_GROUP_DISPLAY (findDisplay BUILD_GROUP_IDD)
#define BUILD_GROUP_FACTIONS (BUILD_GROUP_DISPLAY displayCtrl BUILD_GROUP_FACTIONS_IDC)

#include "\z\potato\addons\core\script_macros.hpp"
