#define COMPONENT reinforceToHC
#include "\z\potato\addons\core\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_REINFORCETOHC
    #define DEBUG_MODE_FULL
#endif

#ifdef DEBUG_SETTINGS_REINFORCETOHC
    #define DEBUG_SETTINGS DEBUG_SETTINGS_REINFORCETOHC
#endif

#define REINFORCEMENT_IDD 945319
#define REINFORCEMENT_FACTIONS_IDC 247916
#define REINFORCEMENT_TYPE_IDC 808579
#define REINFORCEMENT_VEHICLE_IDC 582806
#define REINFORCEMENT_VEHICLE_BEHAVIOR_IDC 380389
#define REINFORCEMENT_VEHICLE_LZ_IDC 919664
#define REINFORCEMENT_UNIT_RP_IDC 839323
#define REINFORCEMENT_UNIT_BEHAVIOR_IDC 921816

#include "\z\potato\addons\core\script_macros.hpp"
