#define COMPONENT safestart
#include "\z\potato\addons\core\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#ifdef DEBUG_ENABLED_SAFESTART
    #define DEBUG_MODE_FULL
#endif
#define QQUOTE(var1) QUOTE(QUOTE(var1))

#define HINT_IDC 1100
#define IDD_SAFESTART 250709
#define IDC_SAFESTARTINFO_DISP 250416
#define IDC_SAFESTARTEQUIP_TEXT 1101
#define IDC_SAFESTARTEQUIP_TITLE 1102
#define IDC_SAFESTARTEQUIP_BACKGROUND 1103
#define IDC_SAFESTARTINFO_BASEGRP 1104

#define SAFESTART_MENU_DEFAULT_X (safeZoneX + (13.6 * ((safeZoneW / safeZoneH) min 1.2) / 40))
#define SAFESTART_MENU_DEFAULT_Y (safeZoneY + 0.01 * safeZoneH)
#define SAFESTART_MENU_DEFAULT_X_QUOTE QUOTE(SAFESTART_MENU_DEFAULT_X)
#define SAFESTART_MENU_DEFAULT_Y_QUOTE QUOTE(SAFESTART_MENU_DEFAULT_Y)
#define SAFESTART_MENU_WIDTH_RAW 9
#define SAFESTART_MENU_WIDTH_NOQUOTE SAFESTART_MENU_WIDTH_RAW * ((safeZoneW / safeZoneH) min 1.2) / 40
#define SAFESTART_MENU_WIDTH QUOTE(SAFESTART_MENU_WIDTH_NOQUOTE)
#define SAFESTART_MENU_WIDTH_ALIGN_NUMBER QUOTE((SAFESTART_MENU_WIDTH_RAW) * ((safeZoneW / safeZoneH) min 1.2) / 40)
#define SAFESTART_MENU_HEIGHT_RAW 15.75
#define SAFESTART_MENU_HEIGHT_NOQUOTE 15.75 * (((safeZoneW / safeZoneH) min 1.2)) / 25
#define SAFESTART_MENU_HEIGHT QUOTE(SAFESTART_MENU_HEIGHT_NOQUOTE)
#define SAFESTART_MENU_OFFSET_X_RAW 0.25
#define SAFESTART_MENU_WIDTH_OFFSET_RAW (SAFESTART_MENU_WIDTH_RAW - 2 * SAFESTART_MENU_OFFSET_X_RAW)
#define SAFESTART_MENU_WIDTH_OFFSET QUOTE(SAFESTART_MENU_WIDTH_OFFSET_RAW  * ((safeZoneW / safeZoneH) min 1.2) / 40)
#define SAFESTART_TEXT_OFFSET_X QUOTE(SAFESTART_MENU_OFFSET_X_RAW * ((safeZoneW / safeZoneH) min 1.2) / 40)

#include "\z\potato\addons\core\script_macros.hpp"
